"""
DataSoul — Google Colab Notebook Export
==========================================
Generates production-ready .ipynb notebooks with:
- Cleaned dataset embedded as code
- Profiling summary as markdown cells
- Pre-written EDA and sklearn pipeline starters
- Threat summary and recommendations
- DataSoul-branded formatting
"""

import json
import io
import pandas as pd
from typing import Optional
from . import IntegrationBase


class GoogleColabIntegration(IntegrationBase):
    name = "google_colab"
    display_name = "Google Colab"
    icon = "📓"
    supports_import = False
    supports_export = True

    def validate_credentials(self, credentials: dict) -> dict:
        """No credentials needed for notebook generation"""
        return {"valid": True, "message": "No authentication required for notebook export"}

    def import_data(self, source: str, credentials: dict | None = None, **kwargs) -> pd.DataFrame:
        raise NotImplementedError("Google Colab integration is export-only")

    def export_data(self, df: pd.DataFrame, destination: str,
                    credentials: dict | None = None,
                    metadata: dict | None = None, **kwargs) -> dict:
        """
        Generate a Colab-ready Jupyter notebook.

        Args:
            df: DataFrame to embed
            destination: Output filename (without .ipynb)
            metadata: Dict with profile, threats, health_score, sector, etc.
        """
        notebook = self._build_notebook(df, destination, metadata or {})
        notebook_json = json.dumps(notebook, indent=2, default=str)

        return {
            "status": "success",
            "notebook": notebook,
            "notebook_json": notebook_json,
            "filename": f"{destination}.ipynb",
            "cells": len(notebook["cells"]),
        }

    def generate_notebook_bytes(self, df: pd.DataFrame, name: str,
                                 metadata: dict | None = None) -> bytes:
        """Generate notebook and return as bytes for download"""
        notebook = self._build_notebook(df, name, metadata or {})
        return json.dumps(notebook, indent=2, default=str).encode("utf-8")

    def _build_notebook(self, df: pd.DataFrame, name: str, metadata: dict) -> dict:
        """Build the full .ipynb notebook structure"""
        cells = []

        # ─── Title cell ───
        cells.append(self._md_cell(f"""# 🧬 DataSoul Intelligence Report: `{name}`

> **Auto-generated by [DataSoul](https://datasoul.ai)** — India's Intelligent Data Readiness Platform

This notebook contains your cleaned, profiled dataset ready for analysis.

---
"""))

        # ─── Metadata summary ───
        profile = metadata.get("profile", {})
        health_score = profile.get("quality_score", {}).get("overall", "N/A")
        grade = profile.get("quality_score", {}).get("grade", "N/A")
        sector = profile.get("sector", {}).get("sector_name", "General") if profile.get("sector") else "General"

        cells.append(self._md_cell(f"""## 📋 Dataset Overview

| Metric | Value |
|--------|-------|
| **Records** | {len(df):,} |
| **Dimensions** | {len(df.columns)} |
| **Health Score** | {health_score}/100 (Grade: {grade}) |
| **Detected Sector** | {sector} |
| **Generated By** | DataSoul AI Engine |
"""))

        # ─── Install dependencies ───
        cells.append(self._code_cell("""# Install dependencies (uncomment if needed)
# !pip install pandas numpy matplotlib seaborn scikit-learn plotly"""))

        # ─── Imports ───
        cells.append(self._code_cell("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO

# Set style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette('husl')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("✅ Libraries loaded successfully")"""))

        # ─── Embed dataset ───
        csv_string = df.to_csv(index=False)
        # Escape triple quotes in CSV
        csv_escaped = csv_string.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')

        cells.append(self._md_cell("## 📦 Load Your Cleaned Dataset"))

        # For large datasets, use a more compact representation
        if len(df) > 1000:
            cells.append(self._code_cell(f"""# Dataset: {len(df):,} rows × {len(df.columns)} columns
# For large datasets, DataSoul embeds the first 1000 rows
# Upload the full cleaned file from DataSoul's Export Center for complete data

csv_data = \"\"\"{df.head(1000).to_csv(index=False)}\"\"\"

df = pd.read_csv(StringIO(csv_data))
print(f"✅ Loaded {{len(df):,}} rows × {{len(df.columns)}} columns")
print(f"⚠️  Showing first 1,000 of {len(df):,} total rows. Upload full file for complete analysis.")
df.head()"""))
        else:
            cells.append(self._code_cell(f"""# Dataset: {len(df):,} rows × {len(df.columns)} columns
csv_data = \"\"\"{csv_string}\"\"\"

df = pd.read_csv(StringIO(csv_data))
print(f"✅ Loaded {{len(df):,}} rows × {{len(df.columns)}} columns")
df.head()"""))

        # ─── Quick EDA ───
        cells.append(self._md_cell("## 🔍 Exploratory Data Analysis"))

        cells.append(self._code_cell("""# Dataset shape and info
print(f"Shape: {df.shape}")
print(f"\\nMemory: {df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB")
print(f"\\nDuplicate rows: {df.duplicated().sum()}")
print(f"\\nMissing values:")
missing = df.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))"""))

        cells.append(self._code_cell("""# Data types and statistics
df.describe(include='all').round(2)"""))

        # ─── Numeric distributions ───
        numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
        if numeric_cols:
            cols_str = str(numeric_cols[:6])
            cells.append(self._md_cell("### 📊 Numeric Distributions"))
            cells.append(self._code_cell(f"""# Distribution of numeric columns
numeric_cols = {cols_str}
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for i, col in enumerate(numeric_cols[:6]):
    if col in df.columns:
        axes[i].hist(df[col].dropna(), bins=30, edgecolor='black', alpha=0.7, color=sns.color_palette('husl')[i])
        axes[i].set_title(col, fontsize=12, fontweight='bold')
        axes[i].set_ylabel('Frequency')

plt.suptitle('Numeric Distributions', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()"""))

        # ─── Categorical analysis ───
        cat_cols = df.select_dtypes(include=["object"]).columns.tolist()
        if cat_cols:
            cols_str = str(cat_cols[:4])
            cells.append(self._md_cell("### 📊 Categorical Analysis"))
            cells.append(self._code_cell(f"""# Top categories
cat_cols = {cols_str}
for col in cat_cols[:4]:
    if col in df.columns:
        print(f"\\n── {{col}} ──")
        print(df[col].value_counts().head(10))
        print()"""))

        # ─── Correlation heatmap ───
        if len(numeric_cols) >= 2:
            cells.append(self._md_cell("### 🔥 Correlation Heatmap"))
            cells.append(self._code_cell("""# Correlation matrix
plt.figure(figsize=(12, 8))
corr = df.select_dtypes(include=[np.number]).corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, square=True, linewidths=0.5)
plt.title('Correlation Heatmap', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()"""))

        # ─── Threats section ───
        threats = metadata.get("threats", {}).get("threats", [])
        if threats:
            cells.append(self._md_cell("## 🛡️ DataSoul Threat Intelligence"))
            threat_md = "| Severity | Threat | Column | Impact |\n|----------|--------|--------|--------|\n"
            for t in threats[:8]:
                sev = "🔴 Critical" if t["severity"] == "critical" else "🟡 Warning" if t["severity"] == "warning" else "🟢 Low"
                threat_md += f"| {sev} | {t['title']} | `{t.get('column', '-')}` | {t.get('impact', '')[:80]} |\n"
            cells.append(self._md_cell(threat_md))

        # ─── ML Pipeline starter ───
        cells.append(self._md_cell("""## 🤖 Machine Learning Pipeline Starter

> Ready-to-use sklearn pipeline. Modify the target column and features as needed.
"""))

        cells.append(self._code_cell("""from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, mean_squared_error, r2_score

# ─── Configure your ML task ───
# TARGET_COLUMN = 'your_target_column'  # Change this!
# TASK = 'classification'  # or 'regression'

# Example pipeline (uncomment and modify):
# X = df.drop(columns=[TARGET_COLUMN])
# y = df[TARGET_COLUMN]
# 
# # Encode categoricals
# for col in X.select_dtypes(include=['object']).columns:
#     X[col] = LabelEncoder().fit_transform(X[col].astype(str))
# 
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)
# 
# model = RandomForestClassifier(n_estimators=100, random_state=42)
# model.fit(X_train_scaled, y_train)
# predictions = model.predict(X_test_scaled)
# print(classification_report(y_test, predictions))

print("🚀 ML pipeline template ready — uncomment and configure above")"""))

        # ─── Footer ───
        cells.append(self._md_cell(f"""---

## 🧬 Powered by DataSoul

This notebook was auto-generated by **DataSoul AI** — India's Intelligent Data Readiness Platform.

- **Health Score**: {health_score}/100
- **Sector**: {sector}
- **Records**: {len(df):,}

> *"Your data, profiled. Your threats, detected. Your story, told."*
"""))

        # Build notebook structure
        return {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {
                    "name": "python",
                    "version": "3.10.0",
                },
                "colab": {
                    "provenance": [],
                    "toc_visible": True,
                },
            },
            "cells": cells,
        }

    @staticmethod
    def _md_cell(content: str) -> dict:
        return {
            "cell_type": "markdown",
            "metadata": {},
            "source": content.split("\n"),
        }

    @staticmethod
    def _code_cell(content: str) -> dict:
        return {
            "cell_type": "code",
            "metadata": {},
            "source": content.split("\n"),
            "outputs": [],
            "execution_count": None,
        }

    def get_status(self) -> dict:
        status = super().get_status()
        status["available"] = True  # No external deps needed for notebook generation
        status["auth_method"] = "none"
        return status
